Repository goorm-growlog/web-ide-be, pull requests merged in 2025-08, with the labels that each got.

#66 Refactor/file system
  src/main/java/com/growlog/webide/domain/files/controller/FileController.java
  src/main/java/com/growlog/webide/domain/files/controller/ProjectMemberController.java
  src/main/java/com/growlog/webide/domain/files/service/FileService.java
  src/main/java/com/growlog/webide/domain/files/service/InstanceService.java
  src/main/java/com/growlog/webide/domain/files/service/ProjectSecurityService.java
Labels: refactor, backend

#64 refactor: 사용자 부분 유효성 검사 dto에 추가
  src/main/java/com/growlog/webide/domain/users/controller/UserController.java
  src/main/java/com/growlog/webide/domain/users/controller/UserMyPageController.java
  src/main/java/com/growlog/webide/domain/users/dto/DeleteRequestDto.java
  src/main/java/com/growlog/webide/domain/users/dto/NameUpdateRequestDto.java
  src/main/java/com/growlog/webide/domain/users/dto/PasswordUpdateRequestDto.java
  src/main/java/com/growlog/webide/domain/users/dto/PasswordVerifyRequestDto.java
  src/main/java/com/growlog/webide/domain/users/dto/UserRegistrationRequestDto.java
Labels: refactor, backend

#74 Feat/refresh token
  .env.sample
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  main-server/src/main/java/com/growlog/webide/domain/auth/controller/AuthController.java
  main-server/src/main/java/com/growlog/webide/domain/auth/dto/RotatedTokens.java
  main-server/src/main/java/com/growlog/webide/domain/auth/dto/TokenResponse.java
  main-server/src/main/java/com/growlog/webide/domain/auth/entity/RefreshToken.java
  main-server/src/main/java/com/growlog/webide/domain/auth/repository/RefreshTokenRepository.java
  main-server/src/main/java/com/growlog/webide/domain/auth/service/AuthService.java
  main-server/src/main/java/com/growlog/webide/global/common/exception/ErrorCode.java
  main-server/src/main/java/com/growlog/webide/global/common/jwt/JwtTokenProvider.java
  main-server/src/main/resources/application.yml
Labels: feat, backend

#80 Feat/rabbitmq setting
  main-server/build.gradle
  main-server/src/main/java/com/growlog/webide/config/RabbitmqConfig.java
  main-server/src/main/resources/application-local.yml
  worker-server/build.gradle
  worker-server/src/main/java/com/growlog/webide/workers/config/RabbitmqConfig.java
  worker-server/src/main/resources/application-local.yml
  worker-server/src/main/resources/application.properties
  worker-server/src/main/resources/application.yml
Labels: chore, backend

#93 Refactor/tree
  main-server/src/main/java/com/growlog/webide/domain/files/controller/ProjectTreeController.java
  main-server/src/main/java/com/growlog/webide/domain/files/controller/TreeWebSocketController.java
  main-server/src/main/java/com/growlog/webide/domain/files/service/FileService.java
  main-server/src/main/java/com/growlog/webide/domain/files/service/ProjectTreeService.java
  main-server/src/main/java/com/growlog/webide/domain/files/service/TreeService.java
Labels: refactor, backend
